// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_EventType int32

const (
	Event_EVENT   Event_EventType = 0
	Event_MEETING Event_EventType = 1
)

var Event_EventType_name = map[int32]string{
	0: "EVENT",
	1: "MEETING",
}

var Event_EventType_value = map[string]int32{
	"EVENT":   0,
	"MEETING": 1,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}

func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0, 0}
}

type Event struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Event_EventType      `protobuf:"varint,3,opt,name=type,proto3,enum=Event_EventType" json:"type,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetType() Event_EventType {
	if m != nil {
		return m.Type
	}
	return Event_EVENT
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Event) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type EventsMap struct {
	Events               map[int32]*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EventsMap) Reset()         { *m = EventsMap{} }
func (m *EventsMap) String() string { return proto.CompactTextString(m) }
func (*EventsMap) ProtoMessage()    {}
func (*EventsMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *EventsMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsMap.Unmarshal(m, b)
}
func (m *EventsMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsMap.Marshal(b, m, deterministic)
}
func (m *EventsMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsMap.Merge(m, src)
}
func (m *EventsMap) XXX_Size() int {
	return xxx_messageInfo_EventsMap.Size(m)
}
func (m *EventsMap) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsMap.DiscardUnknown(m)
}

var xxx_messageInfo_EventsMap proto.InternalMessageInfo

func (m *EventsMap) GetEvents() map[int32]*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*EventsMap)(nil), "EventsMap")
	proto.RegisterMapType((map[int32]*Event)(nil), "EventsMap.EventsEntry")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x31, 0x6b, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0x72, 0x6c, 0xff, 0xf1, 0xb9, 0x04, 0x73, 0x43, 0x11, 0xa1, 0x50, 0x93, 0x76,
	0xf0, 0xa4, 0x80, 0xbb, 0xb4, 0x85, 0x0e, 0x19, 0x4c, 0xe9, 0x90, 0x0c, 0xc2, 0xed, 0x1a, 0x94,
	0xf8, 0x1a, 0x42, 0x1d, 0xdb, 0x38, 0x4a, 0xc0, 0x4b, 0x3f, 0x4b, 0x3f, 0x6a, 0x89, 0xe4, 0x84,
	0x6e, 0x59, 0xc4, 0xbb, 0xbb, 0xdf, 0x3b, 0x9e, 0x0e, 0x86, 0x2b, 0x55, 0x52, 0x55, 0xa8, 0x56,
	0x34, 0x6d, 0xad, 0xeb, 0xd1, 0xed, 0xba, 0xae, 0xd7, 0x25, 0x4d, 0x4c, 0xb5, 0xdc, 0x7f, 0x4e,
	0xf4, 0x66, 0x4b, 0x3b, 0xad, 0xb6, 0x8d, 0x05, 0xc6, 0x3f, 0x0e, 0x78, 0xd9, 0x81, 0x2a, 0x8d,
	0x08, 0x6e, 0xa5, 0xb6, 0xc4, 0x59, 0xcc, 0x92, 0x40, 0x1a, 0x8d, 0x43, 0x70, 0x36, 0x05, 0x77,
	0x62, 0x96, 0x78, 0xd2, 0xd9, 0x14, 0x78, 0x0f, 0xae, 0xee, 0x1a, 0xe2, 0x83, 0x98, 0x25, 0xc3,
	0x34, 0x12, 0xc6, 0x69, 0xdf, 0xbc, 0x6b, 0x48, 0x9a, 0x29, 0x0a, 0x70, 0x0b, 0xa5, 0x89, 0xbb,
	0x31, 0x4b, 0xc2, 0x74, 0x24, 0x6c, 0x06, 0x71, 0xca, 0x20, 0xf2, 0x53, 0x06, 0x69, 0x38, 0x7c,
	0x02, 0x58, 0xb5, 0xa4, 0x34, 0x15, 0x0b, 0xa5, 0xb9, 0x77, 0xd1, 0x15, 0xf4, 0xf4, 0x54, 0xe3,
	0x0b, 0x5c, 0x95, 0x6a, 0xa7, 0x17, 0xfb, 0xe6, 0xb8, 0xa9, 0xe0, 0xfe, 0x45, 0x73, 0x78, 0xe4,
	0xdf, 0x2d, 0x3e, 0xbe, 0x83, 0xe0, 0x1c, 0x1e, 0x03, 0xf0, 0xb2, 0x8f, 0x6c, 0x9e, 0x47, 0xff,
	0x30, 0x84, 0xff, 0xb3, 0x2c, 0xcb, 0xdf, 0xe6, 0xaf, 0x11, 0x1b, 0x7f, 0xf7, 0xd0, 0x6e, 0xa6,
	0x1a, 0x14, 0xe0, 0x93, 0x29, 0x38, 0x8b, 0x07, 0x49, 0x98, 0x5e, 0x8b, 0xf3, 0xac, 0x57, 0x59,
	0xa5, 0xdb, 0x4e, 0xf6, 0xd4, 0x68, 0x0a, 0xe1, 0x9f, 0x36, 0x46, 0x30, 0xf8, 0xa2, 0xce, 0xdc,
	0xd8, 0x93, 0x47, 0x89, 0x37, 0xe0, 0x1d, 0x54, 0xb9, 0x27, 0x73, 0xe5, 0x30, 0xf5, 0xed, 0x16,
	0x69, 0x9b, 0xcf, 0xce, 0x23, 0x5b, 0xfa, 0xe6, 0x17, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xb1, 0x3c, 0xa1, 0xdc, 0x01, 0x00, 0x00,
}
