name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Setup
      run: make setup

    - name: Prepare Lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s latest
    
    - name: Lint 
      run: $GITHUB_WORKSPACE/bin/golangci-lint run --enable-all --disable gochecknoinits --disable gochecknoglobals --disable goimports \
        --out-format=tab --tests=false ./...

    - name: Debug
      run: ls -lRa; pwd; env

    - name: Test
      run: make test

    - name: Build
      run: make build
